### ISSUE TITLE
c++ library

### ISSUE THREAD

**Issue by flovera1** [moses-smt/giza-pp#1]
hi guys, i'm trying to make "make" (haha lol), but i'm getting this error:

./mystl.h:28:10: fatal error: 'tr1/unordered_map' file not found

this is for the calling in line 28 in file mystl.h 

please pin me if you can help me!.

**Comment by hieuhoang** [comment]
What OS and what compiler are you using?

**Comment by flovera1** [comment]
hey man, I'm using macOS Sierra and my c++ compiler is the one
as default from Xcode.

Kind regards,

Fernando A. Lovera
Simon Bolivar's University
-----
 about.me/fernandolovera
<https://about.me/t/r?u=https%3A//about.me/fernandolovera&s=account_creation&i=2395561&k=email_signature_link&t=1378072020>

**Comment by hieuhoang** [comment]
I suggest you use mgiza.
  https://github.com/moses-smt/mgiza
It's compatible with giza++, it's maintained and kept up to date

**Comment by flovera1** [comment]
are you saying that giza++ is not compatible with macos ? Oo

Fernando A. Lovera
Simon Bolivar's University
-----
 about.me/fernandolovera
<https://about.me/t/r?u=https%3A//about.me/fernandolovera&s=account_creation&i=2395561&k=email_signature_link&t=1378072020>

**Comment by hieuhoang** [comment]
doesn't look like it.

**Comment by frankier** [comment]
This can be worked around by:

1. Adding -stdlib=libstdc++ to CFLAGS in the Makefiles of Giza++ and mkcls

2. Changing all references to tr/unordered_map to unordered_map (not tested)

**Comment by stanfordideal** [comment]
I met the problem with `./mystl.h:28:10: fatal error: 'tr1/unordered_map' file not found`
And I wonder if you have solved the problem. If do, please give me a hand, thanks!
