### ISSUE TITLE
Can giza++ work as train-test mode?

### ISSUE THREAD

**Issue by duterscmy** [moses-smt/giza-pp#10]
Assume that now I have lots of parallel sentences, I can use giza++ to obtain the parameters and the align result.
If I have other sentences in future, can I use the obtained parameters above to obtain the align result? (without retraining)

**Comment by duterscmy** [comment]
I have used FastAlign ( a similair tool), and it have a python file ( force_align.py )which can use trained parameter to obtain the align result of new sentences

**Comment by edwardgao** [comment]
You may try:

https://github.com/moses-smt/mgiza/blob/master/mgizapp/scripts/force-align-moses.sh
--Q

**Comment by hieuhoang** [comment]
as Qin  Gao says, use mgiza. Not only is it set up to do force alignment, it's faster and more maintained.

**Comment by duterscmy** [comment]
thanks all above
